/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Lab8 */

#ifndef _Included_Lab8
#define _Included_Lab8
#ifdef __cplusplus
extern "C" {
#endif
#undef Lab8_FOCUS_TRAVERSABLE_UNKNOWN
#define Lab8_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef Lab8_FOCUS_TRAVERSABLE_DEFAULT
#define Lab8_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef Lab8_FOCUS_TRAVERSABLE_SET
#define Lab8_FOCUS_TRAVERSABLE_SET 2L
#undef Lab8_TOP_ALIGNMENT
#define Lab8_TOP_ALIGNMENT 0.0f
#undef Lab8_CENTER_ALIGNMENT
#define Lab8_CENTER_ALIGNMENT 0.5f
#undef Lab8_BOTTOM_ALIGNMENT
#define Lab8_BOTTOM_ALIGNMENT 1.0f
#undef Lab8_LEFT_ALIGNMENT
#define Lab8_LEFT_ALIGNMENT 0.0f
#undef Lab8_RIGHT_ALIGNMENT
#define Lab8_RIGHT_ALIGNMENT 1.0f
#undef Lab8_serialVersionUID
#define Lab8_serialVersionUID -7644114512714619750i64
#undef Lab8_serialVersionUID
#define Lab8_serialVersionUID 4613797578919906343i64
#undef Lab8_INCLUDE_SELF
#define Lab8_INCLUDE_SELF 1L
#undef Lab8_SEARCH_HEAVYWEIGHTS
#define Lab8_SEARCH_HEAVYWEIGHTS 1L
#undef Lab8_OPENED
#define Lab8_OPENED 1L
#undef Lab8_serialVersionUID
#define Lab8_serialVersionUID 4497834738069338734i64
#undef Lab8_DEFAULT_CURSOR
#define Lab8_DEFAULT_CURSOR 0L
#undef Lab8_CROSSHAIR_CURSOR
#define Lab8_CROSSHAIR_CURSOR 1L
#undef Lab8_TEXT_CURSOR
#define Lab8_TEXT_CURSOR 2L
#undef Lab8_WAIT_CURSOR
#define Lab8_WAIT_CURSOR 3L
#undef Lab8_SW_RESIZE_CURSOR
#define Lab8_SW_RESIZE_CURSOR 4L
#undef Lab8_SE_RESIZE_CURSOR
#define Lab8_SE_RESIZE_CURSOR 5L
#undef Lab8_NW_RESIZE_CURSOR
#define Lab8_NW_RESIZE_CURSOR 6L
#undef Lab8_NE_RESIZE_CURSOR
#define Lab8_NE_RESIZE_CURSOR 7L
#undef Lab8_N_RESIZE_CURSOR
#define Lab8_N_RESIZE_CURSOR 8L
#undef Lab8_S_RESIZE_CURSOR
#define Lab8_S_RESIZE_CURSOR 9L
#undef Lab8_W_RESIZE_CURSOR
#define Lab8_W_RESIZE_CURSOR 10L
#undef Lab8_E_RESIZE_CURSOR
#define Lab8_E_RESIZE_CURSOR 11L
#undef Lab8_HAND_CURSOR
#define Lab8_HAND_CURSOR 12L
#undef Lab8_MOVE_CURSOR
#define Lab8_MOVE_CURSOR 13L
#undef Lab8_NORMAL
#define Lab8_NORMAL 0L
#undef Lab8_ICONIFIED
#define Lab8_ICONIFIED 1L
#undef Lab8_MAXIMIZED_HORIZ
#define Lab8_MAXIMIZED_HORIZ 2L
#undef Lab8_MAXIMIZED_VERT
#define Lab8_MAXIMIZED_VERT 4L
#undef Lab8_MAXIMIZED_BOTH
#define Lab8_MAXIMIZED_BOTH 6L
#undef Lab8_serialVersionUID
#define Lab8_serialVersionUID 2673458971256075116i64
#undef Lab8_EXIT_ON_CLOSE
#define Lab8_EXIT_ON_CLOSE 3L
/*
 * Class:     Lab8
 * Method:    calculateMean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Lab8_calculateMean
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Lab8
 * Method:    calculateSTDDev
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Lab8_calculateSTDDev
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
